// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// Eigen_C
List Eigen_C(NumericMatrix As);
RcppExport SEXP _Utility_Eigen_C(SEXP AsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type As(AsSEXP);
    rcpp_result_gen = Rcpp::wrap(Eigen_C(As));
    return rcpp_result_gen;
END_RCPP
}
// Eigen_C_value
Eigen::VectorXd Eigen_C_value(NumericMatrix As);
RcppExport SEXP _Utility_Eigen_C_value(SEXP AsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type As(AsSEXP);
    rcpp_result_gen = Rcpp::wrap(Eigen_C_value(As));
    return rcpp_result_gen;
END_RCPP
}
// tAKA_RC
Rcpp::NumericMatrix tAKA_RC(NumericMatrix A, NumericMatrix K);
RcppExport SEXP _Utility_tAKA_RC(SEXP ASEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(tAKA_RC(A, K));
    return rcpp_result_gen;
END_RCPP
}

RcppExport void tAKA(void *, void *, void *, void *, void *);

static const R_CallMethodDef CallEntries[] = {
    {"_Utility_Eigen_C", (DL_FUNC) &_Utility_Eigen_C, 1},
    {"_Utility_Eigen_C_value", (DL_FUNC) &_Utility_Eigen_C_value, 1},
    {"_Utility_tAKA_RC", (DL_FUNC) &_Utility_tAKA_RC, 2},
    {"tAKA", (DL_FUNC) &tAKA, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_Utility(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
