# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Eigen_C
#' @param As A sysmetric matrix
#' @export
Eigen_C <- function(As) {
    .Call('_Utility_Eigen_C', PACKAGE = 'Utility', As)
}

#' Eigen_C_value
#' @param As A sysmetric matrix
#' @export
Eigen_C_value <- function(As) {
    .Call('_Utility_Eigen_C_value', PACKAGE = 'Utility', As)
}

tAKA_RC <- function(A, K) {
    .Call('_Utility_tAKA_RC', PACKAGE = 'Utility', A, K)
}

