# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Eigen_C
#' @param As A sysmetric matrix
#' @export
Eigen_C <- function(As) {
    .Call('_CKLRT_Eigen_C', PACKAGE = 'CKLRT', As)
}

#' Eigen_C_value
#' @param As A sysmetric matrix
#' @export
Eigen_C_value <- function(As) {
    .Call('_CKLRT_Eigen_C_value', PACKAGE = 'CKLRT', As)
}

#' MatMult_C
#' @param A first matrix
#' @param B second matrix
#' @export
MatMult_C <- function(A, B) {
    .Call('_CKLRT_MatMult_C', PACKAGE = 'CKLRT', A, B)
}

#' Sum_C
#' @param AA Vector
#' @export
Sum_C <- function(AA) {
    .Call('_CKLRT_Sum_C', PACKAGE = 'CKLRT', AA)
}

#' ColSum_C
#' @param AA Matrix
#' @export
ColSum_C <- function(AA) {
    .Call('_CKLRT_ColSum_C', PACKAGE = 'CKLRT', AA)
}

#' MatrixRowMax_C
#' @param AA Matrix
#' @export
MatrixRowMax_C <- function(AA) {
    .Call('_CKLRT_MatrixRowMax_C', PACKAGE = 'CKLRT', AA)
}

#' Elementwisesquare_C
#' @param AA Matrix
#' @export
Elementwisesquare_C <- function(AA) {
    .Call('_CKLRT_Elementwisesquare_C', PACKAGE = 'CKLRT', AA)
}

#' VecMultMat_C
#' @param A Vector
#' @param B Matrix
#' @export
VecMultMat_C <- function(A, B) {
    .Call('_CKLRT_VecMultMat_C', PACKAGE = 'CKLRT', A, B)
}

#' Vecplus_C
#' @param A Vector
#' @param B Vector
#' @export
Vecplus_C <- function(A, B) {
    .Call('_CKLRT_Vecplus_C', PACKAGE = 'CKLRT', A, B)
}

#' ColSumtwomatrix_C
#' @param AA Matrix
#' @param BB Matrix
#' @export
ColSumtwomatrix_C <- function(AA, BB) {
    .Call('_CKLRT_ColSumtwomatrix_C', PACKAGE = 'CKLRT', AA, BB)
}

#' ifelsetest_C
#' @param x Vector
#' @export
ifelsetest_C <- function(x) {
    .Call('_CKLRT_ifelsetest_C', PACKAGE = 'CKLRT', x)
}

#' MatrixPlus_C
#' @param A First Matrix
#' @param B Second Matrix
#' @export
MatrixPlus_C <- function(A, B) {
    .Call('_CKLRT_MatrixPlus_C', PACKAGE = 'CKLRT', A, B)
}

#' NumxMatrix_C
#' @param A Number
#' @param B Matrix
#' @export
NumxMatrix_C <- function(A, B) {
    .Call('_CKLRT_NumxMatrix_C', PACKAGE = 'CKLRT', A, B)
}

#' LR0_fixRho_C
#' @param LamdasR Lamda Number
#' @param muR mu vector
#' @param w1R w1 vector
#' @param w2R w2 vector
#' @param nminuspx n-px
#' @export
LR0_fixRho_C <- function(LamdasR, muR, w1R, w2R, nminuspx) {
    .Call('_CKLRT_LR0_fixRho_C', PACKAGE = 'CKLRT', LamdasR, muR, w1R, w2R, nminuspx)
}

#' doubleloop
#' @param K1R K1 matrix
#' @param K2R K2 matrix
#' @param P0R P0 matrix
#' @param AR A matrix
#' @param U1R U1 vector
#' @param wR w matrix
#' @param LamdasR Lamdas vector
#' @param nminuspx n-px
#' @param all_rho
#'
doubleloop <- function(K1R, K2R, P0R, AR, U1R, wR, LamdasR, nminuspx, all_rho, LR0_allRhoR) {
    .Call('_CKLRT_doubleloop', PACKAGE = 'CKLRT', K1R, K2R, P0R, AR, U1R, wR, LamdasR, nminuspx, all_rho, LR0_allRhoR)
}

#' LR0_fixRho_LRT_C
#' @param LamdasR Lamda Number
#' @param muR mu vector
#' @param w1R w1 vector
#' @param w2R w2 vector
#' @param nminuspx n-px
#' @export
LR0_fixRho_LRT_C <- function(LamdasR, muR, w1R, w2R, nminuspx, xiR) {
    .Call('_CKLRT_LR0_fixRho_LRT_C', PACKAGE = 'CKLRT', LamdasR, muR, w1R, w2R, nminuspx, xiR)
}

#' doubleloop_LRT
#' @param K1R K1 matrix
#' @param K2R K2 matrix
#' @param P0R P0 matrix
#' @param AR A matrix
#' @param U1R U1 vector
#' @param wR w matrix
#' @param LamdasR Lamdas vector
#' @param nminuspx n-px
#' @param all_rho rho vector
#' @param LR0_allRhoR LR0_allRhomatrix
#' @export
doubleloop_LRT <- function(K1R, K2R, P0R, AR, U1R, wR, LamdasR, nminuspx, all_rho, LR0_allRhoR) {
    .Call('_CKLRT_doubleloop_LRT', PACKAGE = 'CKLRT', K1R, K2R, P0R, AR, U1R, wR, LamdasR, nminuspx, all_rho, LR0_allRhoR)
}

