# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Eigen_C
#' @param As A sysmetric matrix
#' @export
Eigen_C <- function(As) {
    .Call('_Utility_Eigen_C', PACKAGE = 'Utility', As)
}

#' Eigen_C_value
#' @param As A sysmetric matrix
#' @export
Eigen_C_value <- function(As) {
    .Call('_Utility_Eigen_C_value', PACKAGE = 'Utility', As)
}

#' MatMult_C
#' @param A first matrix
#' @param B second matrix
#' @export
MatMult_C <- function(A, B) {
    .Call('_Utility_MatMult_C', PACKAGE = 'Utility', A, B)
}

#' Sum_C
#' @param AA Vector
#' @export
Sum_C <- function(AA) {
    .Call('_Utility_Sum_C', PACKAGE = 'Utility', AA)
}

#' ColSum_C
#' @param AA Matrix
#' @export
ColSum_C <- function(AA) {
    .Call('_Utility_ColSum_C', PACKAGE = 'Utility', AA)
}

#' MatrixRowMax_C
#' @param AA Matrix
#' @export
MatrixRowMax_C <- function(AA) {
    .Call('_Utility_MatrixRowMax_C', PACKAGE = 'Utility', AA)
}

#' Elementwisesquare_C
#' @param AA Matrix
#' @export
Elementwisesquare_C <- function(AA) {
    .Call('_Utility_Elementwisesquare_C', PACKAGE = 'Utility', AA)
}

#' VecMultMat_C
#' @param A Vector
#' @param B Matrix
#' @export
VecMultMat_C <- function(A, B) {
    .Call('_Utility_VecMultMat_C', PACKAGE = 'Utility', A, B)
}

#' Vecplus_C
#' @param A Vector
#' @param B Vector
#' @export
Vecplus_C <- function(A, B) {
    .Call('_Utility_Vecplus_C', PACKAGE = 'Utility', A, B)
}

#' ColSumtwomatrix_C
#' @param AA Matrix
#' @param BB Matrix
#' @export
ColSumtwomatrix_C <- function(AA, BB) {
    .Call('_Utility_ColSumtwomatrix_C', PACKAGE = 'Utility', AA, BB)
}

#' ifelsetest_C
#' @param x Vector
#' @export
ifelsetest_C <- function(x) {
    .Call('_Utility_ifelsetest_C', PACKAGE = 'Utility', x)
}

#' MatrixPlus_C
#' @param A First Matrix
#' @param B Second Matrix
#' @export
MatrixPlus_C <- function(A, B) {
    .Call('_Utility_MatrixPlus_C', PACKAGE = 'Utility', A, B)
}

#' NumxMatrix_C
#' @param A Number
#' @param B Matrix
#' @export
NumxMatrix_C <- function(A, B) {
    .Call('_Utility_NumxMatrix_C', PACKAGE = 'Utility', A, B)
}

#' LR0_fixRho_C
#' @param LamdasR Lamda Number
#' @param muR mu vector
#' @param w1R w1 vector
#' @param w2R w2 vector
#' @param nminuspx n-px
#' @export
LR0_fixRho_C <- function(LamdasR, muR, w1R, w2R, nminuspx) {
    .Call('_Utility_LR0_fixRho_C', PACKAGE = 'Utility', LamdasR, muR, w1R, w2R, nminuspx)
}

#' doubleloop
#' @param K1R K1 matrix
#' @param K2R K2 matrix
#' @param P0R P0 matrix
#' @param AR A matrix
#' @param U1R U1 vector
#' @param wR w matrix
#' @param LamdasR Lamdas vector
#' @param nminuspx n-px
#' @param all_rho
#' @export
doubleloop <- function(K1R, K2R, P0R, AR, U1R, wR, LamdasR, nminuspx, all_rho, LR0_allRhoR) {
    .Call('_Utility_doubleloop', PACKAGE = 'Utility', K1R, K2R, P0R, AR, U1R, wR, LamdasR, nminuspx, all_rho, LR0_allRhoR)
}

#' LR0_fixRho_LRT_C
#' @param LamdasR Lamda Number
#' @param muR mu vector
#' @param w1R w1 vector
#' @param w2R w2 vector
#' @param nminuspx n-px
#' @export
LR0_fixRho_LRT_C <- function(LamdasR, muR, w1R, w2R, nminuspx, xiR) {
    .Call('_Utility_LR0_fixRho_LRT_C', PACKAGE = 'Utility', LamdasR, muR, w1R, w2R, nminuspx, xiR)
}

#' doubleloop_LRT
#' @param K1R K1 matrix
#' @param K2R K2 matrix
#' @param P0R P0 matrix
#' @param AR A matrix
#' @param U1R U1 vector
#' @param wR w matrix
#' @param LamdasR Lamdas vector
#' @param nminuspx n-px
#' @param all_rho
#' @export
doubleloop_LRT <- function(K1R, K2R, P0R, AR, U1R, wR, LamdasR, nminuspx, all_rho, LR0_allRhoR) {
    .Call('_Utility_doubleloop_LRT', PACKAGE = 'Utility', K1R, K2R, P0R, AR, U1R, wR, LamdasR, nminuspx, all_rho, LR0_allRhoR)
}

